// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  datasource: {
    // The CLI (migrate/generate/studio) connects directly, bypassing the
    // pooler — the app itself connects separately via DATABASE_URL in
    // src/lib/prisma.ts, using the pooled connection.
    // DATABASE_URL_UNPOOLED is provided automatically by Vercel's Neon
    // integration (the "non-pooling" connection string).
    url: process.env["DATABASE_URL_UNPOOLED"] ?? process.env["DATABASE_URL"],
  },
});
